### ISSUE TITLE
How to work on local environment?

### ISSUE THREAD

**Issue by adeleke5140** [johnpolacek/date-range-picker-for-shadcn#1]
I wanted to help fix a bug I noticed on mobile for your website and then proceeded to fork the repo.
Sadly I wasn't able to run the project locally and inspecting `package.json` doesn't seem to include any `npm` script.

Could you give me some pointers?

**Comment by johnpolacek** [comment]
Follow the steps in the [shadcn documentation](https://ui.shadcn.com/docs) to configure your project. Then follow the steps in the date range picker instructions as it follows the same pattern as other shadcn ui components.
